[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  identifier = "articles"
  name = "Articles"
  url = "posts"
  weight = 2

[[main]]
  identifier = "examples"
  name = "Examples"
  url = "examples"
  weight = 3

[[main]]
  identifier = "worksheets"
  name = "Worksheets"
  url = "worksheets"
  weight = 4

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 5

