[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  identifier = "articles"
  name = "Articles"
  url = "Articles"
  weight = 2

[[main]]
  parent = "articles"
  name = "Physics"
  url = "/categories/Physics"

[[main]]
  parent = "articles"
  name = "Math"
  url = "/categories/Math"

[[main]]
  identifier = "solutions"
  name = "Solutions"
  url = "solutions"
  weight = 3

[[main]]
  parent = "solutions"
  name = "AP Physics"
  url = "solutions/AP-Physics"

[[main]]
  parent = "solutions"
  name = "AP Math"
  url = "solutions/AP-Math"

[[main]]
  parent = "solutions"
  name = "BC Physics"
  url = "solutions/BC-Physics"

[[main]]
  identifier = "sample-papers"
  name = "Sample Papers"
  url = "sample-papers"
  weight = 4

[[main]]
  parent = "sample-papers"
  name = "AP Physics"
  url = "sample-papers/AP-Physics"

[[main]]
  parent = "sample-papers"
  name = "AP Math"
  url = "sample-papers/AP-Math"

[[main]]
  parent = "sample-papers"
  name = "BC Physics"
  url = "sample-papers/BC-Physics"

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 5

